[package]
name = "benchmarks"
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"
homepage = "https://github.com/RustyViT"

[dependencies]
criterion = { workspace = true }

[[bench]]
name = "bm_convolution"
path = "bm_convolution.rs"
harness = false